//! Builder for constructing a `BlogRegistry`.

use crate::blog::registry::BlogRegistry;
use crate::config::ThemeConfig;

/// Builder for constructing a [`BlogRegistry`] from a build-time content bundle.
///
/// # Example
///
/// ```rust,ignore
/// let registry = BlogConfig::new(dioxus_docs_kit::blog_bundle!())
///     .with_posts_per_page(9)
///     .with_theme_toggle("light", "dark", "dark")
///     .build();
/// ```
pub struct BlogConfig {
    bundle_json: &'static str,
    posts_per_page: usize,
    date_format: String,
    theme: Option<ThemeConfig>,
    category_base_path: Option<String>,
}

impl BlogConfig {
    /// Create a new builder from the blog bundle generated by
    /// `dioxus-docs-kit-build`.
    ///
    /// Pass [`blog_bundle!()`](crate::blog_bundle), which embeds
    /// `$OUT_DIR/blog_bundle.json` with `include_str!`.
    pub fn new(bundle_json: &'static str) -> Self {
        Self {
            bundle_json,
            posts_per_page: 9,
            date_format: "%B %d, %Y".to_string(),
            theme: None,
            category_base_path: None,
        }
    }

    /// Set the number of posts per page for pagination (default: 9).
    pub fn with_posts_per_page(mut self, n: usize) -> Self {
        self.posts_per_page = n;
        self
    }

    /// Enable linkable tag categories under a root-relative path.
    ///
    /// Register routes for `{base}/:slug` and `{base}/:slug/page/:page`
    /// rendering [`crate::BlogCategoryPage`] (page numbers start at one).
    /// With this unset, existing tag buttons retain their local filtering behavior
    /// and no category URLs are emitted into the sitemap.
    pub fn with_category_base_path(mut self, path: &str) -> Self {
        self.category_base_path = Some(path.trim_end_matches('/').to_string());
        self
    }

    pub(crate) fn category_base_path(&self) -> Option<&str> {
        self.category_base_path.as_deref()
    }

    /// Set the date display format (default: "%B %d, %Y").
    pub fn with_date_format(mut self, fmt: &str) -> Self {
        self.date_format = fmt.to_string();
        self
    }

    /// Set a single theme (no toggle button).
    pub fn with_theme(mut self, theme: &str) -> Self {
        self.theme = Some(ThemeConfig {
            default_theme: theme.to_string(),
            toggle_themes: None,
            storage_key: "docs-theme".to_string(),
        });
        self
    }

    /// Enable a light/dark theme toggle.
    pub fn with_theme_toggle(mut self, light: &str, dark: &str, default: &str) -> Self {
        self.theme = Some(ThemeConfig {
            default_theme: default.to_string(),
            toggle_themes: Some((light.to_string(), dark.to_string())),
            storage_key: "docs-theme".to_string(),
        });
        self
    }

    /// Build the [`BlogRegistry`].
    ///
    /// # Panics
    ///
    /// Panics with a descriptive message if the blog bundle fails to
    /// deserialize. Use [`Self::try_build`] to handle the error yourself.
    pub fn build(self) -> BlogRegistry {
        self.try_build()
            .unwrap_or_else(|e| panic!("dioxus-docs-kit: {e}"))
    }

    /// Build the [`BlogRegistry`], returning an error instead of panicking when
    /// the blog bundle cannot be read.
    pub fn try_build(self) -> Result<BlogRegistry, crate::error::DocsKitError> {
        BlogRegistry::try_from_config(self)
    }

    pub(crate) fn bundle_json(&self) -> &str {
        self.bundle_json
    }

    pub(crate) fn posts_per_page(&self) -> usize {
        self.posts_per_page
    }

    pub(crate) fn date_format(&self) -> &str {
        &self.date_format
    }

    pub(crate) fn theme_config(&self) -> Option<&ThemeConfig> {
        self.theme.as_ref()
    }
}
