//! Builder for constructing a `DocsRegistry`.

use crate::registry::DocsRegistry;
#[cfg(feature = "highlight")]
use dioxus_code::Theme;

/// Theme configuration for the documentation site.
///
/// Controls which DaisyUI theme(s) are applied and whether a toggle button is shown.
#[derive(Clone, Debug, PartialEq)]
pub struct ThemeConfig {
    /// The default theme name (must match a DaisyUI theme defined in `tailwind.css`).
    pub default_theme: String,
    /// If set, enables a light/dark toggle button. Tuple is `(light_theme, dark_theme)`.
    pub toggle_themes: Option<(String, String)>,
    /// localStorage key used to persist the user's theme preference.
    pub storage_key: String,
}

/// How rendered code blocks pick their syntax-highlighting theme.
///
/// Defaults to [`CodeThemeConfig::Adaptive`] with GitHub Light / Tokyo Night.
///
/// Only available with the `highlight` feature (default), which pulls in `dioxus-code`.
#[cfg(feature = "highlight")]
#[derive(Clone, Copy, Debug)]
#[non_exhaustive]
pub enum CodeThemeConfig {
    /// Always use this one theme, regardless of the site's light/dark state.
    Fixed(Theme),
    /// Pick `light` or `dark` to match the site theme.
    ///
    /// When a light/dark toggle is configured (via [`DocsConfig::with_theme_toggle`]),
    /// the choice tracks the active `data-theme` (not the OS `prefers-color-scheme`),
    /// so code blocks stay in sync with the toggle. Without a toggle it falls back to
    /// `prefers-color-scheme`.
    Adaptive {
        /// Theme used when the site is in its light state.
        light: Theme,
        /// Theme used when the site is in its dark state.
        dark: Theme,
    },
}

#[cfg(feature = "highlight")]
impl Default for CodeThemeConfig {
    fn default() -> Self {
        Self::Adaptive {
            light: Theme::GITHUB_LIGHT,
            dark: Theme::TOKYO_NIGHT,
        }
    }
}

/// Builder for constructing a [`DocsRegistry`] from a build-time content bundle.
///
/// # Example
///
/// ```rust,ignore
/// let registry = DocsConfig::new(dioxus_docs_kit::docs_bundle!())
///     .with_default_path("getting-started/introduction")
///     .build();
/// ```
///
/// Pages and OpenAPI specs come from the bundle, so they are configured in
/// `build.rs` (see `dioxus_docs_kit_build::DocsBuild`), not here.
pub struct DocsConfig {
    bundle_json: &'static str,
    default_path: Option<String>,
    api_group_name: Option<String>,
    theme: Option<ThemeConfig>,
    #[cfg(feature = "highlight")]
    code_theme: CodeThemeConfig,
}

impl DocsConfig {
    /// Create a new builder from the content bundle generated by
    /// `dioxus-docs-kit-build`.
    ///
    /// Pass [`docs_bundle!()`](crate::docs_bundle), which embeds
    /// `$OUT_DIR/docs_bundle.json` with `include_str!`. Nothing is deserialized
    /// until [`build`](Self::build) runs, so a `LazyLock<DocsRegistry>` static
    /// stays free until the first page render.
    pub fn new(bundle_json: &'static str) -> Self {
        Self {
            bundle_json,
            default_path: None,
            api_group_name: None,
            theme: None,
            #[cfg(feature = "highlight")]
            code_theme: CodeThemeConfig::default(),
        }
    }

    /// Set the default documentation path for redirects.
    ///
    /// Defaults to the first page in the first nav group if not set.
    pub fn with_default_path(mut self, path: &str) -> Self {
        self.default_path = Some(path.to_string());
        self
    }

    /// Set the display name for the API Reference sidebar group.
    ///
    /// Defaults to `"API Reference"`. The value must match a `"group"` in
    /// `_nav.json` so the library knows where to inject the API endpoint sidebar
    /// entries; do **not** list individual operation paths in that group's
    /// `"pages"` array.
    pub fn with_api_group_name(mut self, name: &str) -> Self {
        self.api_group_name = Some(name.to_string());
        self
    }

    /// Set a single theme (no toggle button).
    ///
    /// The theme name must match a DaisyUI theme defined in the consumer's `tailwind.css`.
    pub fn with_theme(mut self, theme: &str) -> Self {
        self.theme = Some(ThemeConfig {
            default_theme: theme.to_string(),
            toggle_themes: None,
            storage_key: "docs-theme".to_string(),
        });
        self
    }

    /// Enable a light/dark theme toggle.
    ///
    /// - `light`: Name of the light DaisyUI theme.
    /// - `dark`: Name of the dark DaisyUI theme.
    /// - `default`: Which of the two to use on first visit (`light` or `dark`).
    pub fn with_theme_toggle(mut self, light: &str, dark: &str, default: &str) -> Self {
        self.theme = Some(ThemeConfig {
            default_theme: default.to_string(),
            toggle_themes: Some((light.to_string(), dark.to_string())),
            storage_key: "docs-theme".to_string(),
        });
        self
    }

    /// Use a single, fixed syntax-highlighting theme for all code blocks.
    ///
    /// Use this for single-theme sites (e.g. a dark-only app) so the code block
    /// background matches the site instead of following the reader's OS setting.
    ///
    /// Only available with the `highlight` feature (default), which pulls in `dioxus-code`.
    #[cfg(feature = "highlight")]
    pub fn with_code_theme(mut self, theme: Theme) -> Self {
        self.code_theme = CodeThemeConfig::Fixed(theme);
        self
    }

    /// Use a light/dark pair of syntax themes for code blocks.
    ///
    /// When a theme toggle is configured (see [`Self::with_theme_toggle`]), the active
    /// choice tracks the toggle's `data-theme`; otherwise it follows the reader's OS
    /// `prefers-color-scheme`. Defaults to GitHub Light / Tokyo Night when not set.
    ///
    /// Only available with the `highlight` feature (default), which pulls in `dioxus-code`.
    #[cfg(feature = "highlight")]
    pub fn with_code_themes(mut self, light: Theme, dark: Theme) -> Self {
        self.code_theme = CodeThemeConfig::Adaptive { light, dark };
        self
    }

    /// Build the [`DocsRegistry`].
    ///
    /// Deserializes the content bundle: pages, OpenAPI specs and the search
    /// index are all already parsed.
    ///
    /// # Panics
    ///
    /// Panics with a descriptive message if the bundle fails to deserialize or
    /// was produced by an incompatible `dioxus-docs-kit-build`. Use
    /// [`Self::try_build`] to handle these errors yourself.
    pub fn build(self) -> DocsRegistry {
        self.try_build()
            .unwrap_or_else(|e| panic!("dioxus-docs-kit: {e}"))
    }

    /// Build the [`DocsRegistry`], returning an error instead of panicking when
    /// the content bundle cannot be read.
    pub fn try_build(self) -> Result<DocsRegistry, crate::error::DocsKitError> {
        DocsRegistry::try_from_config(self)
    }

    // Accessors for DocsRegistry::try_from_config
    pub(crate) fn bundle_json(&self) -> &str {
        self.bundle_json
    }

    pub(crate) fn default_path_value(&self) -> Option<&str> {
        self.default_path.as_deref()
    }

    pub(crate) fn api_group_name_value(&self) -> Option<&str> {
        self.api_group_name.as_deref()
    }

    pub(crate) fn theme_config(&self) -> Option<&ThemeConfig> {
        self.theme.as_ref()
    }

    #[cfg(feature = "highlight")]
    pub(crate) fn code_theme_value(&self) -> CodeThemeConfig {
        self.code_theme
    }
}
