//! Error types for registry construction.

/// Errors produced when building a [`DocsRegistry`](crate::DocsRegistry) or
/// [`BlogRegistry`](crate::blog::BlogRegistry) from a build-time content bundle.
#[derive(Debug)]
#[non_exhaustive]
pub enum DocsKitError {
    /// The docs bundle (`docs_bundle!()`) failed to deserialize.
    DocsBundleParse(serde_json::Error),
    /// The blog bundle (`blog_bundle!()`) failed to deserialize.
    BlogBundleParse(serde_json::Error),
    /// A bundle was generated by an incompatible `dioxus-docs-kit-build`.
    BundleVersion {
        /// The version the bundle declares.
        found: u32,
        /// The version this library understands.
        expected: u32,
    },
    /// Invalid blog configuration (for example, ambiguous category slugs).
    BlogConfig(String),
}

impl std::fmt::Display for DocsKitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::DocsBundleParse(e) => write!(f, "failed to parse the docs bundle: {e}"),
            Self::BlogBundleParse(e) => write!(f, "failed to parse the blog bundle: {e}"),
            Self::BundleVersion { found, expected } => write!(
                f,
                "content bundle format v{found} was generated by a different \
                 dioxus-docs-kit-build (this library reads v{expected}) — \
                 keep dioxus-docs-kit and dioxus-docs-kit-build on the same version"
            ),
            Self::BlogConfig(message) => write!(f, "invalid blog configuration: {message}"),
        }
    }
}

impl std::error::Error for DocsKitError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::DocsBundleParse(e) | Self::BlogBundleParse(e) => Some(e),
            Self::BundleVersion { .. } | Self::BlogConfig(_) => None,
        }
    }
}
