#!/usr/bin/env python3
"""Regenerate `crates/dioxus-mdx/src/lucide.rs` from the upstream Lucide icon data.

Scans the workspace for `Ld*` icon names that are actually used, pulls the
matching SVG child elements out of a copy of `dioxus-free-icons`' `ld_icons.rs`,
and writes them out as `&'static str` constants. Run it only when the set of
used icons changes:

    python3 scripts/vendor-lucide-icons.py \
        ~/.cargo/registry/src/*/dioxus-free-icons-0.10.0/src/icons/ld_icons.rs

The generated file is committed; nothing at build time needs this script.
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "crates/dioxus-mdx/src/lucide.rs"

HEADER = '''//! Vendored [Lucide](https://lucide.dev) icons.
//!
//! Generated by `scripts/vendor-lucide-icons.py` — do not edit by hand. Only the
//! icons this workspace actually renders are vendored; every one is a 24x24
//! stroke icon, so [`Icon`] hard-codes the shared `<svg>` attributes and each
//! constant carries just the inner elements.
//!
//! Lucide icons are ISC licensed:
//!
//! > ISC License
//! >
//! > Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as
//! > part of Feather (MIT). All other copyright (c) for Lucide are held by
//! > Lucide Contributors 2022.
//! >
//! > Permission to use, copy, modify, and/or distribute this software for any
//! > purpose with or without fee is hereby granted, provided that the above
//! > copyright notice and this permission notice appear in all copies.
//! >
//! > THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
//! > WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
//! > MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
//! > ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
//! > WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
//! > ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
//! > IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use dioxus::prelude::*;

/// A Lucide icon: the inner elements of a 24x24 stroke `<svg>`.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct LucideIcon(&'static str);

/// Renders a [`LucideIcon`] as an inline `<svg>`.
#[component]
pub fn Icon(
    /// The icon to draw.
    icon: LucideIcon,
    /// Classes for the `<svg>` element.
    #[props(default = String::new())]
    class: String,
) -> Element {
    rsx! {
        svg {
            class: "{class}",
            height: "20",
            width: "20",
            view_box: "0 0 24 24",
            xmlns: "http://www.w3.org/2000/svg",
            fill: "none",
            stroke: "currentColor",
            stroke_width: "2",
            stroke_linecap: "round",
            stroke_linejoin: "round",
            dangerous_inner_html: icon.0,
        }
    }
}

#[allow(non_upper_case_globals)]
mod data {
    use super::LucideIcon;

'''

FOOTER = "}\n\npub use data::*;\n"


def used_icons() -> set:
    out = subprocess.run(
        [
            "grep",
            "-rhoE",
            r"\bLd[A-Z][A-Za-z0-9]*",
            "crates/dioxus-docs-kit/src",
            "crates/dioxus-mdx/src",
            "src",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return set(out.split())


def parse_upstream(path: Path) -> dict:
    src = path.read_text()
    icons = {}
    for block in src.split("#[derive(Copy, Clone, Debug, PartialEq)]\n")[1:]:
        name = re.match(r"pub struct (\w+);", block)
        if not name:
            continue
        body = re.search(
            r"fn child_elements\(&self\) -> Element \{\s*rsx! \{(.*?)\n        \}\n    \}",
            block,
            re.S,
        )
        if not body:
            continue
        svg = ""
        for tag, attrs in re.findall(r"(\w+) \{([^{}]*)\}", body.group(1)):
            pairs = re.findall(r'(\w+): "((?:[^"\\]|\\.)*)"', attrs)
            rendered = "".join(' {}="{}"'.format(k, v) for k, v in pairs)
            svg += "<{}{}/>".format(tag, rendered)
        icons[name.group(1)] = svg
    return icons


def main() -> None:
    upstream = parse_upstream(Path(sys.argv[1]))
    lines = []
    for name in sorted(used_icons()):
        if name not in upstream:
            sys.exit("unknown icon: " + name)
        body = upstream[name]
        assert '"#' not in body
        lines.append(
            '    pub const {}: LucideIcon = LucideIcon(r#"{}"#);\n'.format(name, body)
        )
    OUT.write_text(HEADER + "".join(lines) + FOOTER)
    print("wrote {} icons to {}".format(len(lines), OUT))


if __name__ == "__main__":
    main()
